### ISSUE TITLE
たまにエラー吐く

### ISSUE THREAD

**Issue by hirossan4049** [hirossan4049/ZisakuZiten-share-api#1]
```
2020-10-06T17:37:34.440823+00:00 app[web.1]: title='らからあら' updateTime='2020-10-07 01:55:32' ziten_updT_List=[Ziten(title='やたらた', content='た、たら', updateTime='2020-10-07 01:55:40')]
2020-10-06T17:37:34.441508+00:00 app[web.1]: INFO:     IP:0 - "POST /post/ HTTP/1.1" 500 Internal Server Error
2020-10-06T17:37:34.442580+00:00 app[web.1]: ERROR:    Exception in ASGI application
2020-10-06T17:37:34.442581+00:00 app[web.1]: Traceback (most recent call last):
2020-10-06T17:37:34.442583+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
2020-10-06T17:37:34.442584+00:00 app[web.1]:     result = await app(self.scope, self.receive, self.send)
2020-10-06T17:37:34.442584+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
2020-10-06T17:37:34.442584+00:00 app[web.1]:     return await self.app(scope, receive, send)
2020-10-06T17:37:34.442585+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/fastapi/applications.py", line 181, in __call__
2020-10-06T17:37:34.442586+00:00 app[web.1]:     await super().__call__(scope, receive, send)  # pragma: no cover
2020-10-06T17:37:34.442586+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/starlette/applications.py", line 111, in __call__
2020-10-06T17:37:34.442586+00:00 app[web.1]:     await self.middleware_stack(scope, receive, send)
2020-10-06T17:37:34.442587+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
2020-10-06T17:37:34.442587+00:00 app[web.1]:     raise exc from None
2020-10-06T17:37:34.442588+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
2020-10-06T17:37:34.442588+00:00 app[web.1]:     await self.app(scope, receive, _send)
2020-10-06T17:37:34.442588+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
2020-10-06T17:37:34.442589+00:00 app[web.1]:     raise exc from None
2020-10-06T17:37:34.442589+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
2020-10-06T17:37:34.442589+00:00 app[web.1]:     await self.app(scope, receive, sender)
2020-10-06T17:37:34.442589+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/starlette/routing.py", line 566, in __call__
2020-10-06T17:37:34.442590+00:00 app[web.1]:     await route.handle(scope, receive, send)
2020-10-06T17:37:34.442590+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/starlette/routing.py", line 227, in handle
2020-10-06T17:37:34.442590+00:00 app[web.1]:     await self.app(scope, receive, send)
2020-10-06T17:37:34.442591+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/starlette/routing.py", line 41, in app
2020-10-06T17:37:34.442591+00:00 app[web.1]:     response = await func(request)
2020-10-06T17:37:34.442591+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/fastapi/routing.py", line 183, in app
2020-10-06T17:37:34.442591+00:00 app[web.1]:     dependant=dependant, values=values, is_coroutine=is_coroutine
2020-10-06T17:37:34.442591+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
2020-10-06T17:37:34.442592+00:00 app[web.1]:     return await dependant.call(**values)
2020-10-06T17:37:34.442592+00:00 app[web.1]:   File "./app/main.py", line 66, in create_group
2020-10-06T17:37:34.442592+00:00 app[web.1]:     db.set(id,passwd,group.json())
2020-10-06T17:37:34.442592+00:00 app[web.1]:   File "./app/db.py", line 10, in set
2020-10-06T17:37:34.442593+00:00 app[web.1]:     self.db.insert({'id':id, 'passwd':passwd,'utime': int(time()), 'data':data})
2020-10-06T17:37:34.442593+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/tinydb/table.py", line 170, in insert
2020-10-06T17:37:34.442593+00:00 app[web.1]:     self._update_table(updater)
2020-10-06T17:37:34.442593+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/tinydb/table.py", line 641, in _update_table
2020-10-06T17:37:34.442594+00:00 app[web.1]:     updater(table)
2020-10-06T17:37:34.442594+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/tinydb/table.py", line 162, in updater
2020-10-06T17:37:34.442594+00:00 app[web.1]:     assert doc_id not in table, 'doc_id '+str(doc_id)+' already exists'
2020-10-06T17:37:34.442597+00:00 app[web.1]: AssertionError: doc_id 7 already exists
2020-10-06T17:37:34.444485+00:00 heroku[router]: at=info method=POST path="/post/" host=http3.herokuapp.com ```

**Comment by hirossan4049** [comment]
違うエラー。

```
2020-10-08T08:06:56.894439+00:00 heroku[router]: sock=backend at=error code=H18 desc="Server Request Interrupted" method=POST path="/post" host=http3.herokuapp.com request_id=184d9c38-740f-4a37-9e8b-1d1e26082c2d fwd="IP" dyno=web.1 connect=1ms service=2ms status=503 bytes= protocol=https
```
